import { NextResponse } from "next/server";
import { askGemma } from "@/lib/ollama";
import type { LearnerProfile, GeneratedPlan, GeneratedTask, MissedReason, ClientTask } from "@/lib/types";

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const profile: LearnerProfile = body.profile;
    const today: string = body.today;
    const missedTask: ClientTask = body.missedTask;
    const missedReason: MissedReason = body.missedReason;
    const recentTaskHistory: ClientTask[] = body.recentTaskHistory;
    const pendingFutureTasks: ClientTask[] = body.pendingFutureTasks;
    const remainingAvailableTime: Record<string, number> = body.remainingAvailableTime;

    if (!profile || !today || !missedTask || !missedReason) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
    }

    const validDates = Object.keys(remainingAvailableTime).sort();
    if (validDates.length === 0) {
      return NextResponse.json({ error: "No valid future dates to schedule tasks." }, { status: 400 });
    }

    // 1. Build explicit prompt for Gemma Adaptation
    const prompt = `
You are an expert, adaptive study planner. The student has missed a task and needs an adapted plan for the remaining days.

STUDENT PROFILE:
- Goal: ${profile.goal}
- Deadline: ${profile.deadline}
- Strong Topics: ${profile.strongTopics?.join(", ") || "None"}
- Weak Topics: ${profile.weakTopics?.join(", ") || "None"}

MISSED TASK:
- Title: ${missedTask.title} (${missedTask.topic})
- Type: ${missedTask.kind}
- Original Duration: ${missedTask.minutes} mins
- Date Missed: ${missedReason.date}

REASON FOR MISSING:
- Reason: ${missedReason.reason}
- Explanation: ${missedReason.explanation || "N/A"}

FUTURE PENDING TASKS (These need to be replaced/redistributed):
${pendingFutureTasks.map(t => `- [${t.date}] ${t.title} (${t.minutes} mins)`).join("\n") || "None"}

AVAILABLE STUDY SLOTS (DO NOT INVENT OTHER DATES, DO NOT EXCEED THESE MINUTES):
${validDates.map(date => `- ${date}: ${remainingAvailableTime[date]} minutes remaining`).join("\n")}

RULES:
1. You MUST ONLY use the exact dates listed in the available slots above.
2. The total 'minutes' of all tasks on a specific date MUST NOT exceed the minutes available for that date.
3. ADAPT INTELLIGENTLY based on the missed reason:
   - If "Exhausted" or "Sick", make the next study day lighter.
   - If a surprise deadline occurred, redistribute work smoothly across remaining slots.
   - If less time was available, respect the reduced available time.
4. Prioritize weak topics.
5. NEVER simply stack all missed work on top of tomorrow. Be realistic.
6. Return the newly adapted future plan STRICTLY as JSON matching the schema.
7. Provide a short, friendly "message" (2-3 sentences) explaining what changed and why it changed based on their reason.
`;

    // 2. Ask Gemma
    const rawPlan = await askGemma(prompt) as any;

    // 3. Manual Server-Side Validation
    if (!rawPlan || typeof rawPlan !== "object") {
      throw new Error("Invalid response format from Gemma: not an object.");
    }
    if (typeof rawPlan.message !== "string") {
      throw new Error("Invalid response: 'message' must be a string.");
    }
    if (!Array.isArray(rawPlan.tasks)) {
      throw new Error("Invalid response: 'tasks' must be an array.");
    }

    const dateToUsedMinutes = new Map<string, number>();
    const validDatesSet = new Set(validDates);
    const validatedTasks: GeneratedTask[] = [];

    for (const task of rawPlan.tasks) {
      if (typeof task.date !== "string" || 
          typeof task.topic !== "string" || 
          typeof task.title !== "string" || 
          typeof task.minutes !== "number" || 
          typeof task.kind !== "string") {
        throw new Error("Invalid task format. Missing or incorrect types.");
      }

      if (task.minutes <= 0) {
        throw new Error("Task minutes must be positive.");
      }

      if (!["learn", "practice", "review"].includes(task.kind)) {
        throw new Error("Task kind must be 'learn', 'practice', or 'review'.");
      }

      if (!validDatesSet.has(task.date)) {
        throw new Error(`Invalid date '${task.date}' generated by Gemma.`);
      }

      const currentUsed = dateToUsedMinutes.get(task.date) || 0;
      const newUsed = currentUsed + task.minutes;
      const allowed = remainingAvailableTime[task.date]!;

      if (newUsed > allowed) {
        throw new Error(`Total minutes for ${task.date} exceeded allowed limit (${allowed} mins).`);
      }

      dateToUsedMinutes.set(task.date, newUsed);
      
      validatedTasks.push({
        date: task.date,
        topic: task.topic,
        title: task.title,
        minutes: task.minutes,
        kind: task.kind as "learn" | "practice" | "review"
      });
    }

    const validatedPlan: GeneratedPlan = {
      message: rawPlan.message,
      tasks: validatedTasks,
    };

    return NextResponse.json({ success: true, plan: validatedPlan });

  } catch (error: any) {
    console.error("Adaptation Error:", error);
    return NextResponse.json({ error: error.message || "Failed to adapt plan." }, { status: 500 });
  }
}
