import { NextResponse } from "next/server";
import { askGemma } from "@/lib/ollama";
import type { LearnerProfile, GeneratedPlan, GeneratedTask } from "@/lib/types";

// Helper to add days to a date string (YYYY-MM-DD)
function addDays(dateStr: string, days: number): string {
  const d = new Date(dateStr);
  d.setDate(d.getDate() + days);
  return d.toISOString().split("T")[0];
}

export async function POST(req: Request) {
  try {
    const { profile, today } = await req.json() as { profile: LearnerProfile, today: string };

    if (!profile || !today) {
      return NextResponse.json({ error: "Missing profile or today" }, { status: 400 });
    }

    const { deadline, dailyMinutes, constraints, strongTopics, weakTopics } = profile;

    // 1. Server-side slot calculation
    const slots: { date: string; minutes: number }[] = [];
    
    // We plan for up to 7 days, starting from 'today'
    for (let i = 0; i < 7; i++) {
      const currentDate = addDays(today, i);
      
      // Do not generate dates after the deadline
      if (currentDate > deadline) {
        break;
      }
      
      slots.push({
        date: currentDate,
        minutes: dailyMinutes
      });
    }

    if (slots.length === 0) {
      return NextResponse.json({ error: "No valid study days before deadline." }, { status: 400 });
    }

    const validDates = new Set(slots.map(s => s.date));
    const maxMinutesPerDate = new Map(slots.map(s => [s.date, s.minutes]));

    // 2. Build explicit prompt for Gemma
    const prompt = `
You are an expert study planner. Create a realistic, highly specific study plan based on the strict constraints below.

STUDENT PROFILE:
- Goal: ${profile.goal}
- Constraints: ${profile.constraints}
- Strong Topics (lighter review): ${strongTopics.join(", ") || "None"}
- Weak Topics (more attention): ${weakTopics.join(", ") || "None"}

AVAILABLE STUDY SLOTS (DO NOT INVENT OTHER DATES, DO NOT EXCEED THESE MINUTES):
${slots.map(s => `- ${s.date}: ${s.minutes} minutes`).join("\n")}

RULES:
1. You MUST ONLY use the exact dates listed in the available slots above.
2. The total 'minutes' of all tasks on a specific date MUST NOT exceed the minutes available for that date.
3. Dedicate more time to weak topics and less to strong topics.
4. Maintain a good balance of "learn", "practice", and "review" tasks.
5. Provide a short, encouraging "message" summarizing the plan.
6. Return the plan STRICTLY as structured JSON matching the provided schema.
`;

    // 3. Ask Gemma
    const rawPlan = await askGemma(prompt) as any;

    // 4. Manual Server-Side Validation
    if (!rawPlan || typeof rawPlan !== "object") {
      throw new Error("Invalid response format from Gemma: not an object.");
    }

    if (typeof rawPlan.message !== "string") {
      throw new Error("Invalid response: 'message' must be a string.");
    }

    if (!Array.isArray(rawPlan.tasks)) {
      throw new Error("Invalid response: 'tasks' must be an array.");
    }

    const dateToUsedMinutes = new Map<string, number>();

    const validatedTasks: GeneratedTask[] = [];

    for (const task of rawPlan.tasks) {
      if (typeof task.date !== "string" || 
          typeof task.topic !== "string" || 
          typeof task.title !== "string" || 
          typeof task.minutes !== "number" || 
          typeof task.kind !== "string") {
        throw new Error("Invalid task format. Missing or incorrect types.");
      }

      if (task.minutes <= 0) {
        throw new Error("Task minutes must be positive.");
      }

      if (!["learn", "practice", "review"].includes(task.kind)) {
        throw new Error("Task kind must be 'learn', 'practice', or 'review'.");
      }

      if (!validDates.has(task.date)) {
        throw new Error(`Invalid date '${task.date}' generated by Gemma.`);
      }

      const currentUsed = dateToUsedMinutes.get(task.date) || 0;
      const newUsed = currentUsed + task.minutes;
      const allowed = maxMinutesPerDate.get(task.date)!;

      if (newUsed > allowed) {
        throw new Error(`Total minutes for ${task.date} exceeded allowed limit (${allowed} mins).`);
      }

      dateToUsedMinutes.set(task.date, newUsed);
      
      validatedTasks.push({
        date: task.date,
        topic: task.topic,
        title: task.title,
        minutes: task.minutes,
        kind: task.kind as "learn" | "practice" | "review"
      });
    }

    const validatedPlan: GeneratedPlan = {
      message: rawPlan.message,
      tasks: validatedTasks,
    };

    return NextResponse.json({ success: true, plan: validatedPlan });

  } catch (error: any) {
    console.error("Plan Generation Error:", error);
    return NextResponse.json({ error: error.message || "Failed to generate plan." }, { status: 500 });
  }
}
